name: femu
description: "emulator"
version: 0.0.1
homepage: https://github.com/xiaohuihuiold/femu
repository: https://github.com/xiaohuihuiold/femu

environment:
  sdk: '>=3.3.0-214.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  date_format: ^2.0.7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
