part of 'gb_rom.dart';

enum GBCartridgeType {
  RomOnly(0x00, 'ROM ONLY'),
  MBC1(0x01, 'MBC1'),
  MBC1RAM(0x02, 'MBC1+RAM'),
  MBC1RAMBattery(0x03, 'MBC1+RAM+BATTERY'),
  MBC2(0x05, 'MBC2'),
  MBC2Battery(0x06, 'MBC2+BATTERY'),
  RomRAM(0x08, 'ROM+RAM'),
  RomRAMBattery(0x09, 'ROM+RAM+BATTERY'),
  MMM01(0x0B, 'MMM01'),
  MMM01RAM(0x0C, 'MMM01+RAM'),
  MMM01RAMBattery(0x0D, 'MMM01+RAM+BATTERY'),
  MBC3TimerBattery(0x0F, 'MBC3+TIMER+BATTERY'),
  MBC3TimerRAMBattery(0x10, 'MBC3+TIMER+RAM+BATTERY'),
  MBC3(0x11, 'MBC3'),
  MBC3RAM(0x12, 'MBC3+RAM'),
  MBC3RAMBattery(0x13, 'MBC3+RAM+BATTERY'),
  MBC5(0x19, 'MBC5'),
  MBC5RAM(0x1A, 'MBC5+RAM'),
  MBC5RAMBattery(0x1B, 'MBC5+RAM+BATTERY'),
  MBC5Rumble(0x1C, 'MBC5+RUMBLE'),
  MBC5RumbleRAM(0x1D, 'MBC5+RUMBLE+RAM'),
  MBC5RumbleRAMBattery(0x1E, 'MBC5+RUMBLE+RAM+BATTERY'),
  MBC6(0x20, 'MBC6'),
  MBC7SensorRumbleRAMBattery(0x22, 'MBC7+SENSOR+RUMBLE+RAM+BATTERY'),
  POCKETCamera(0xFC, 'POCKET CAMERA'),
  BANDAITAMA5(0xFD, 'BANDAI TAMA5'),
  HUC3(0xFE, 'HuC3'),
  HUC1RAMBattery(0xFF, 'HuC1+RAM+BATTERY');

  final int code;
  final String name;

  const GBCartridgeType(this.code, this.name);
}

enum GBOldLicenseeCode {
  None(0x00, 'None'),
  Nintendo(0x31, 'Nintendo'),
  Capcom(0x08, 'Capcom'),
  HOB(0x09, 'HOT-B'),
  Jaleco(0x0A, 'Jaleco'),
  CoconutsJapan(0x0B, 'Coconuts Japan'),
  EliteSystems(0x0C, 'Elite Systems'),
  EA(0x13, 'EA (Electronic Arts)'),
  HudsonSoft(0x18, 'Hudson Soft'),
  ITCEntertainment(0x19, 'ITC Entertainment'),
  Yanoman(0x1A, 'Yanoman'),
  JapanClary(0x1D, 'Japan Clary'),
  VirginGamesLtd(0x1F, 'Virgin Games Ltd.'),
  PCMComplete(0x24, 'PCM Complete'),
  SanX(0x25, 'San-X'),
  Kemco(0x28, 'Kemco'),
  SETACorporation(0x29, 'SETA Corporation'),
  Infogrames(0x30, 'Infogrames'),
  Bandai(0x32, 'Bandai'),
  Konami(0x34, 'Konami'),
  HectorSoft(0x35, 'HectorSoft'),
  Capcom2(0x38, 'Capcom'),
  Banpresto(0x39, 'Banpresto'),
  Entertainmenti(0x3C, '.Entertainment i'),
  Gremlin(0x3E, 'Gremlin'),
  UbiSoft1(0x41, 'Ubi Soft1'),
  Atlus(0x42, 'Atlus'),
  MalibuInteractive(0x44, 'Malibu Interactive'),
  Angel(0x46, 'Angel'),
  SpectrumHoloby(0x47, 'Spectrum Holoby'),
  Irem(0x49, 'Irem'),
  VirginGamesLtd2(0x4A, 'Virgin Games Ltd.'),
  MalibuInteractive2(0x4D, 'Malibu Interactive'),
  USGold(0x4F, 'U.S. Gold'),
  Absolute(0x50, 'Absolute'),
  AcclaimEntertainment(0x51, 'Acclaim Entertainment'),
  Activision(0x52, 'Activision'),
  SammyUSACorporation(0x53, 'Sammy USA Corporation'),
  GameTek(0x54, 'GameTek'),
  ParkPlace(0x55, 'Park Place'),
  LJN(0x56, 'LJN'),
  Matchbox(0x57, 'Matchbox'),
  MiltonBradleyCompany(0x59, 'Milton Bradley Company'),
  Mindscape(0x5A, 'Mindscape'),
  Romstar(0x5B, 'Romstar'),
  NaxatSoft(0x5C, 'Naxat Soft'),
  Tradewest(0x5D, 'Tradewest'),
  TitusInteractive(0x60, 'Titus Interactive'),
  VirginGamesLtd3(0x61, 'Virgin Games Ltd.'),
  OceanSoftware(0x67, 'Ocean Software'),
  EA2(0x69, 'EA (Electronic Arts)'),
  EliteSystems2(0x6E, 'Elite Systems'),
  ElectroBrain(0x6F, 'Electro Brain'),
  Infogrames2(0x70, 'Infogrames5'),
  InterplayEntertainment(0x71, 'Interplay Entertainment'),
  Broderbund(0x72, 'Broderbund'),
  SculpturedSoftware(0x73, 'Sculptured Software'),
  TheSalesCurveLimited(0x75, 'The Sales Curve Limited'),
  THQ(0x78, 'THQ'),
  Accolade(0x79, 'Accolade'),
  TriffixEntertainment(0x7A, 'Triffix Entertainment'),
  Microprose(0x7C, 'Microprose'),
  Kemco2(0x7F, 'Kemco'),
  MisawaEntertainment(0x80, 'Misawa Entertainment'),
  Lozc(0x83, 'Lozc'),
  TokumaShoten(0x86, 'Tokuma Shoten'),
  BulletProofSoftware(0x8B, 'Bullet-Proof Software'),
  VicTokai(0x8C, 'Vic Tokai'),
  Ape(0x8E, 'Ape'),
  IMax(0x8F, 'I’Max'),
  ChunsoftCo(0x91, 'Chunsoft Co.'),
  VideoSystem(0x92, 'Video System'),
  Varie(0x95, 'Varie'),
  YonezawaSPal(0x96, 'Yonezawa/S’Pal'),
  Kemco3(0x97, 'Kemco'),
  PackInVideo(0x99, 'Pack-In-Video'),
  NihonBussan(0x9A, 'Nihon Bussan'),
  Tecmo(0x9B, 'Tecmo'),
  Imagineer(0x9C, 'Imagineer'),
  Banpresto2(0x9D, 'Banpresto'),
  Nova(0x9F, 'Nova'),
  HoriElectric(0xA1, 'Hori Electric'),
  Bandai2(0xA2, 'Bandai'),
  Konami2(0xA4, 'Konami'),
  Kawada(0xA6, 'Kawada'),
  Takara(0xA7, 'Takara'),
  TechnosJapan(0xA9, 'Technos Japan'),
  Broderbund2(0xAA, 'Broderbund'),
  ToeiAnimation(0xAC, 'Toei Animation'),
  Toho(0xAD, 'Toho'),
  Namco(0xAF, 'Namco'),
  AcclaimEntertainment2(0xB0, 'Acclaim Entertainment'),
  ASCIICorporationorNexsoft(0xB1, 'ASCII Corporation or Nexsoft'),
  Bandai3(0xB2, 'Bandai'),
  SquareEnix(0xB4, 'Square Enix'),
  HALLaboratory(0xB6, 'HAL Laboratory'),
  SNK(0xB7, 'SNK'),
  PonyCanyon(0xB9, 'Pony Canyon'),
  CultureBrain(0xBA, 'Culture Brain'),
  Sunsoft(0xBB, 'Sunsoft'),
  SonyImagesoft(0xBD, 'Sony Imagesoft'),
  SammyCorporation(0xBF, 'Sammy Corporation'),
  Taito(0xC0, 'Taito'),
  Kemco4(0xC2, 'Kemco'),
  Square(0xC3, 'Square'),
  TokumaShoten2(0xC4, 'Tokuma Shoten'),
  DataEast(0xC5, 'Data East'),
  Tonkinhouse(0xC6, 'Tonkinhouse'),
  Koei(0xC8, 'Koei'),
  UFL(0xC9, 'UFL'),
  Ultra(0xCA, 'Ultra'),
  Vap(0xCB, 'Vap'),
  UseCorporation(0xCC, 'Use Corporation'),
  Meldac(0xCD, 'Meldac'),
  PonyCanyon2(0xCE, 'Pony Canyon'),
  Angel2(0xCF, 'Angel'),
  Taito2(0xD0, 'Taito'),
  Sofel(0xD1, 'Sofel'),
  Quest(0xD2, 'Quest'),
  SigmaEnterprises(0xD3, 'Sigma Enterprises'),
  ASKKodanshaCo(0xD4, 'ASK Kodansha Co.'),
  NaxatSoft13(0xD6, 'Naxat Soft13'),
  CopyaSystem(0xD7, 'Copya System'),
  Banpresto3(0xD9, 'Banpresto'),
  Tomy(0xDA, 'Tomy'),
  LJN2(0xDB, 'LJN'),
  NCS(0xDD, 'NCS'),
  Human(0xDE, 'Human'),
  Altron(0xDF, 'Altron'),
  Jaleco2(0xE0, 'Jaleco'),
  TowaChiki(0xE1, 'Towa Chiki'),
  Yutaka(0xE2, 'Yutaka'),
  Varie2(0xE3, 'Varie'),
  Epcoh(0xE5, 'Epcoh'),
  Athena(0xE7, 'Athena'),
  AsmikAceEntertainment(0xE8, 'Asmik Ace Entertainment'),
  Natsume(0xE9, 'Natsume'),
  KingRecords(0xEA, 'King Records'),
  Atlus2(0xEB, 'Atlus'),
  EpicSonyRecords(0xEC, 'Epic/Sony Records'),
  IGS(0xEE, 'IGS'),
  AWave(0xF0, 'A Wave'),
  ExtremeEntertainment(0xF3, 'Extreme Entertainment'),
  LJN3(0xFF, 'LJN');

  final int code;
  final String publisher;

  const GBOldLicenseeCode(this.code, this.publisher);
}

enum GBNewLicenseeCode {
  None('00', 'None'),
  NintendoResearchDevelopment('01', 'NintendoResearch & Development'),
  Capcom('08', 'Capcom'),
  EaElectronicArts('13', 'Ea (ElectronicArts)'),
  HudsonSoft('18', 'HudsonSoft'),
  BAi('19', 'BAi'),
  Kss('20', 'Kss'),
  PlanningOfficeWada('22', 'PlanningOfficeWada'),
  PCmComplete('24', 'PcmComplete'),
  SanX('25', 'SanX'),
  Kemco('28', 'Kemco'),
  SEtaCorporation('29', 'SetaCorporation'),
  Viacom('30', 'Viacom'),
  Nintendo('31', 'Nintendo'),
  Bandai('32', 'Bandai'),
  OceanSoftwareAcclaimEntertainment('33', 'OceanSoftware/AcclaimEntertainment'),
  Konami('34', 'Konami'),
  HectorSoft('35', 'HectorSoft'),
  Taito('37', 'Taito'),
  Banpresto('39', 'Banpresto'),
  UbiSoft1('41', 'UbiSoft1'),
  Atlus('42', 'Atlus'),
  MalibuInteractive('44', 'MalibuInteractive'),
  Angel('46', 'Angel'),
  BulletProofSoftware('47', 'BulletProofSoftware'),
  Irem('49', 'Irem'),
  Absolute('50', 'Absolute'),
  AcclaimEntertainment('51', 'AcclaimEntertainment'),
  Activision('52', 'Activision'),
  SammyUsaCorporation('53', 'SammyUsaCorporation'),
  HiTechExpressions('55', 'HiTechExpressions'),
  Ljn('56', 'Ljn'),
  Matchbox('57', 'Matchbox'),
  Mattel('58', 'Mattel'),
  MiltonBradleyCompany('59', 'MiltonBradleyCompany'),
  TitusInteractive('60', 'TitusInteractive'),
  VirginGamesLtd('61', 'VirginGamesLtd.'),
  LucasfilmGames('64', 'LucasfilmGames'),
  OceanSoftware('67', 'OceanSoftware'),
  Infogrames('70', 'Infogrames'),
  InterplayEntertainment('71', 'InterplayEntertainment'),
  Broderbund('72', 'Broderbund'),
  SculpturedSoftware('73', 'SculpturedSoftware'),
  TheSalesCurveLimited('75', 'TheSalesCurveLimited'),
  THq('78', 'Thq'),
  Accolade('79', 'Accolade'),
  MisawaEntertainment('80', 'MisawaEntertainment'),
  Lozc('83', 'Lozc'),
  TokumaShoten('86', 'TokumaShoten'),
  TsukudaOriginal('87', 'TsukudaOriginal'),
  ChunsoftCo('91', 'ChunsoftCo.'),
  VideoSystem('92', 'VideoSystem'),
  Varie('95', 'Varie'),
  YonezawasPal('96', 'Yonezawa/S’Pal'),
  Kaneko('97', 'Kaneko'),
  PackInVideo('99', 'PackInVideo'),
  BottomUp('9H', 'BottomUp'),
  KonamiYuGiOh('A4', 'Konami (YuGiOh!)'),
  Mto('Bl', 'Mto'),
  Kodansha('Dk', 'Kodansha');

  final String code;
  final String publisher;

  const GBNewLicenseeCode(this.code, this.publisher);
}
